interface_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # My Apps
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('iw_app.urls', namespace='iw_app'))
]

iw_app/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # add urls for pagination
    url(r'^(?P<page_id>\d+)/$', views.index, name='index'),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article, name='article'),
    # add urls for filter modes
    url(r'^(?P<filter_mode>p|c|n|o)/$', views.index, name='index'),
    url(r'^(?P<page_id>\d+)/(?P<filter_mode>p|c|n|o)/$', views.index, name='index'),
    # add url for site information board
    url(r'^site_information/$', views.about_contact, name='information'),
    # add urls for mod panel AND comment moderation panel
    url(r'^site_infrastructure/', include([
        #Redirects to a page will all flagged comments mods will have the option to delete or reset the flagged count to zero.
        url(r'^mod/$', views.content_moderation, name='content_moderation'),
        #This view will also show all of the authors created articles.
        url(r'^staging/$', views.article_staging_all, name='staging_all'),
        # This is an in-depth view into an individual article.
        url(r'^staging/(?P<staged_article>[0-9]+)/$', views.article_staging_individual, name='staging_indv'),
    ])),
    # add urls for article creation AND article editing
    url(r'^author_panel/', include([
        url(r'^new_draft/$', views.new_draft, name='new_draft'),
        url(r'^new_draft/(?P<filter_m>l|e|t)/$', views.new_draft, name='new_draft'),
        url(r'^edit_draft/(?P<draft_id>[0-9]+)/$', views.edit_draft, name='edit_draft'),
        url(r'^edit_article/(?P<article_id>[0-9]+)/$', views.edit_article, name='edit_article'),
    ])),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Register page
    url(r'^register/', views.register_view, name='register')
]

iw_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class ArticleBase(models.Model):
    """
    Defines an Article, will link to a disparate html page or
    to a premade 'link page'
    """
    article_name = models.CharField(max_length=140)
    article_external_url = models.CharField(blank=True, max_length=1000)
    date_created = models.DateTimeField(auto_now_add=True)
    name_author = models.ManyToManyField(User, blank=True)
    article_description = models.TextField(null=True, blank=True)
    article_body_text = models.TextField(null=True, blank=True)
    article_caption_styles = models.TextField(null=True,blank=True)
    LINK = 'LI'
    EDITORIAL = 'ED'
    TUTORIAL = 'TU'
    ARTICLE_TYPES = (
        (LINK, 'link'),
        (EDITORIAL, 'editorial'),
        (TUTORIAL, 'tutorial'),
    )
    article_type = models.CharField(
        max_length=2,
        choices = ARTICLE_TYPES,
        default = LINK,
    )
    class Meta:
        abstract = True


class Article(ArticleBase):

    def __str__(self):
        """Return a string with the articles name"""
        return self.article_name[:50] + '...'


class Draft(ArticleBase):

    draft_vote = models.IntegerField(default=0)
    make_public = models.BooleanField(default=False)
    voters = models.ManyToManyField(User, related_name='voters', blank=True)

    def __str__(self):
        """Return a string desribing a draft """
        return self.article_name[:50] + '...'


class Comment(models.Model):
    comment_text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    comment_on = models.ForeignKey(Article, null=True)
    comment_owner = models.ForeignKey(User, null=True)
    commented_anonymously = models.BooleanField(default=False)
    comment_flag = models.IntegerField(default=0) # incremement based on ban.
    comment_ban_text = models.CharField(max_length=140, null=True)

    def __str__(self):
        """Return a string with an abridged comment"""
        return self.comment_text + str(self.id)


# Discussion of articles belongs in IRC but there could be critque comments too...

iw_app/views.py
from django.shortcuts import render
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Article, Comment, Draft
from .forms import CommentForm, DraftFormLink, DraftFormEditorial, DraftFormTutorial, ArticleFormLink, ArticleFormEditorial, ArticleFormTutorial
from django.contrib.auth.decorators import login_required, user_passes_test

# Security views access to restricted areas of the site.
def not_in_author_group(user):
    if user:
        return user.groups.filter(name='Author').exists()
    return False

def not_in_mod_group(user):
    if user:
        return user.groups.filter(name='Mod').exists()
    return False

# Create your views here.
def index(request, page_id=1, filter_mode='n'):
    """IW_app Index page"""

    if filter_mode == 'p':# list articles by comment_set length
        articles_list = Article.objects.annotate(num_comments=Count('comment')).order_by('-num_comments')

    elif filter_mode == 'c':# list articles with only original content. ie tutorial and editorial type articles.
        articles_list = Article.objects.all().exclude(article_type = "LI")
    elif filter_mode == 'o': # list oldest articles first
        articles_list = Article.objects.all().order_by("pk")
    else: # in most cases this should be n (newest items first)
        filter_mode = 'n'
        articles_list = Article.objects.all().order_by("-pk")

    paginator = Paginator(articles_list, 10) # Show 10 Articles per page

    try:
        articles = paginator.page(page_id)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    context = {'articles': articles, 'filter_mode':filter_mode}

    return render(request, 'iw_app/index.html', context)
    #articles = Article.objects.all().order_by("-pk")
    #context = {'articles': articles}
    #return render(request, 'iw_app/index.html', context)



def article(request, article_id):
    """ Return a given article from a url """
    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Nothing here")

    if request.method != 'POST':
        # No data submitted return article and blank form
        form = CommentForm()
    else:
        # POST data submitted; process data.
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.comment_on = article
            if request.user.is_authenticated():
                new_comment.comment_owner = request.user
            if 'anon_post' in request.POST:
                new_comment.commented_anonymously = True
            new_comment.save()
            return HttpResponseRedirect(reverse('iw_app:article',args=[article_id]))

    form = CommentForm()
    comments = article.comment_set.order_by("date_created")
    context = {'article': article, 'comments': comments, 'form': form, request:'request'}
    return render(request, 'iw_app/article.html', context)



def about_contact(request):
    """ Return a simple about page that describes the site and provides contact info for the admins."""
    context = {request:'request'}
    return render(request, 'iw_app/about.html', context)


@login_required
@user_passes_test(not_in_mod_group, login_url='/users/login/', redirect_field_name=None)
def content_moderation(request):
    """
    View flagged posts by post w/ the most flags provide interface
    to delete those posts.
    """


@login_required
@user_passes_test(not_in_author_group, login_url='/users/login/', redirect_field_name=None)
def article_staging_all(request):
    """
    Show all articles that are currently being considered, provide a comment
    thread for each article for authors to talk on, and possible revision history
    of each article. As well as voting.
    """

    drafts = Draft.objects.all().exclude(make_public = False).order_by('-pk')
    my_drafts = Draft.objects.all().filter(name_author=request.user).order_by('-pk')
    my_articles = Article.objects.all().filter(name_author=request.user).order_by('-pk')

    if request.method == 'POST':
        if request.POST.get('make_public_swap'):
            draft_id = int(request.POST.get('make_public_swap'))
            draft = Draft.objects.get(id=draft_id)
            if draft not in my_drafts:
                return  HttpResponseRedirect(reverse('iw_app:staging_all'))
            if draft.make_public == True:
                draft.make_public = False
                draft.save()
            else:
                draft.make_public = True
                draft.save()
        elif request.POST.get('vote_article'):
            draft_id = int(request.POST.get('vote_article'))
            draft = Draft.objects.get(id=draft_id)
            #TODO add a condition that prevents authors from boosting their own articles.
            if Draft.objects.all().filter(id=draft_id, voters=request.user).exists():
                return  HttpResponseRedirect(reverse('iw_app:staging_all'))
                #If user has already voted, redirected to draft page.
            else:
                #print('vote could be acceptable')
                draft.voters.add(request.user)
                draft.draft_vote += 1
                draft.save()
                if draft.draft_vote >= 2: # This condition determines how many votes a draft needs to succeed.
                    new_article_from_draft(draft)
        return  HttpResponseRedirect(reverse('iw_app:staging_all'))

    context = { 'request' :request ,
                'drafts' :drafts ,
                'my_drafts':my_drafts,
                'my_articles':my_articles,
                }
    return render(request, 'iw_app/staging_area.html', context)



def new_article_from_draft(draft):
    """
    If a draft gains enough votes, create a new article from that draft
    """
    new_article = Article(  article_name = draft.article_name,
                            article_external_url = draft.article_external_url,
                            #name_author = draft.name_author,
                            article_description = draft.article_description,
                            article_body_text = draft.article_body_text,
                            article_caption_styles = draft.article_caption_styles,
                            article_type = draft.article_type,
                            )

    new_article.save()
    old_authors = draft.name_author.all()
    new_article.name_author = old_authors
    new_article.save()
    draft.delete()
    print(old_authors)
    print(new_article.id)


@login_required
@user_passes_test(not_in_author_group, login_url='/users/login/', redirect_field_name=None)
def article_staging_individual(request, staged_article):
    """
    View the article in a template and vote on the article
    """
    article = Draft.objects.get(id=staged_article)
    context = { 'request':request,
                'article': article
                }
    return render(request, 'iw_app/staging_individual.html', context)


@login_required
@user_passes_test(not_in_author_group, login_url='/users/login/', redirect_field_name=None)
def new_draft(request, filter_m ='l'):
    """
    Redo code pertaining to the creation of new drafts
    """
    # Determine what kind of draft is being created.
    if filter_m == 'e':
        draft_type = 'ED'
    elif filter_m == 't':
        draft_type = 'TU'
    else:
        draft_type = 'LI'
    # If request is not = to post return the right kind of form.
    if request.method != 'POST':
        if draft_type == 'ED':
            form = DraftFormEditorial(request.user.id)
        elif draft_type == 'TU':
            form = DraftFormTutorial(request.user.id)
        else:
            form = DraftFormLink(request.user.id)
    # If request IS post. validate form.
    else:
        if draft_type == 'ED':
            form = DraftFormEditorial(request.user.id, request.POST)
        elif draft_type == 'TU':
            form = DraftFormTutorial(request.user.id, request.POST)
        else:
            form = DraftFormLink(request.user.id, request.POST)
        # Check the validity of the form and fill fields if valid.
        if form.is_valid():
            new_draft = form.save(commit=False)
            new_draft.article_type = draft_type
            new_draft.save()
            # This is super important
            form.save_m2m()
            new_draft.name_author.add(request.user)
            # Redirect back to staging area.
            return HttpResponseRedirect(reverse('iw_app:staging_all'))

    context = {'form': form, 'filter_m': filter_m}
    return render(request, 'iw_app/edit_article_draft.html', context)


@login_required
@user_passes_test(not_in_author_group, login_url='/users/login/', redirect_field_name=None)
def edit_draft(request, draft_id):
    """
    This is the interface where the author can edit an articles draft.
    """
    draft = Draft.objects.get(id=draft_id)

    if request.method != 'POST':
        if draft.article_type == 'LI':
            form = DraftFormLink(request.user.id, instance=draft)
        elif draft.article_type == 'ED':
            form = DraftFormEditorial(request.user.id, instance=draft)
        else:
            form = DraftFormTutorial(request.user.id, instance=draft)
    else:
        if draft.article_type == 'LI':
            form = DraftFormLink(request.user.id, instance=draft, data=request.POST)
        elif draft.article_type == 'ED':
            form = DraftFormEditorial(request.user.id, instance=draft, data=request.POST)
        else:
            form = DraftFormTutorial(request.user.id, instance=draft, data=request.POST)
        #Check form validity
        if form.is_valid():
            form.save()
            draft.name_author.add(request.user)

iw_app/templates/iw_app/about.html
{% extends "iw_app/base.html" %}
{% load static %}

{% block content %}
<main id="about_contact">
  <header>
    <h3>INTERFACE MAGAZINE</h3>
  </header>
  <article>
    <p>Interface/Interfa.su is a quarterly cyberpunk zine. I will be using this website to compile articles for the zine before each quarterly release. The most interesting articles and tutorials on this website will be adapted to paper and shipped with the first edition of Interface. We're looking for more people to author articles right now, if you like the content on this site and you'd like to contribute, get in touch at <a href="mailto:webmaster@example.com">c4rdinal@protonmail.com</a>
    </p>
    <p>
    I'd also like to thank <a href="https://lainchan.org/zine" target="blank">Lainzine</a> and the users at <a href="https://lainchan.org" target="blank">Lainchan</a> as well as my friends in <a href="http://emvystudio.com/">meat-space</a> for the inspiration behind this project check them out.
    </p>
    <p>
      Stay safe, c4rdinal
    </p>
  </article>
</main>
{% endblock content %}

iw_app/templates/iw_app/base.html
{% load static %}
<html>

<head>
<link rel="stylesheet" type="text/css" href="{% static "iw_app/css/style_main.css" %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

{% if filter_mode == null %}
  <a href='{% url "iw_app:index" %}' class='return_index'>|<span class='small'>&nbsp;&lArr;</span><span class='big'>&emsp;</span> 界面<span class='big'>&nbsp;Interface Magazine&emsp;</span><span class='small'>&nbsp;</span>|</a>
{% endif %}

<div class='login'>
{% if user.is_authenticated %}
  Hello, <span class="known_post">{{ user.username }}</span>&ensp;
  <a href="{% url 'users:logout'%}">|&emsp;log_out&emsp;|</a>&ensp;
{% else %}
  <a href="{% url 'users:login' %}">|&emsp;log_in / register&emsp;|</a>
{% endif %}

{% if request != null %}
  {% if request.get_full_path != "/site_information/"%}
    &ensp;<a href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
  {% else %}
    &ensp;<a class="focus" href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
  {% endif %}
{% else %}
    &ensp;<a href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
{% endif %}
</div>

{% block content %}



{% endblock content %}
{% load iw_extra %}

<div class="user_author">
{% if request.user|has_group:"Author" %}
   <a href="{% url 'iw_app:staging_all'%}">|&emsp;author_tools&emsp;|</a>
{% endif %}
</div>

</html>

iw_app/templates/iw_app/edit_article_draft.html
{% extends "iw_app/modified_base.html" %}

{% load static %}
{% block content %}
<style>
  main{
    margin-top: 100px;
  }
  h4{
    margin-bottom: 10px;
  }
  .hr{
    margin-top: 10px;
  }
  #delete_button{
    float:right;
  }
  #delete_button:hover{
    background-color: red;
  }
</style>
<main>
{% if draft.id %}
<h4>Draft:{{ draft.id }}&emsp;{{ draft.article_name }}</h4>
{% elif article.id %}
<h4>Article:{{ article.id }}&emsp;{{ article.article_name }}</h4>
{% else %}
<section id='article_type'>
  <p><strong>Article Type:</strong>&emsp;
  <span class="nav_filter">
    {% if filter_m == "l" %}
    <a class="focus" href="/author_panel/new_draft/l">|&emsp;Link&emsp;|</a>
    {% else %}
    <a href="/author_panel/new_draft/l">|&emsp;Link&emsp;|</a>
    {% endif %}
  </span>
  &emsp;
  <span class="nav_filter">
    {% if filter_m == "e" %}
    <a class="focus" href="/author_panel/new_draft/e">|&emsp;Editorial&emsp;|</a>
    {% else %}
    <a href="/author_panel/new_draft/e">|&emsp;Editorial&emsp;|</a>
    {% endif %}
  </span>
  &emsp;
  <span class="nav_filter">
    {% if filter_m == "t" %}
    <a class="focus" href="/author_panel/new_draft/t">|&emsp;Tutorial&emsp;|</a>
    {% else %}
    <a href="/author_panel/new_draft/t">|&emsp;Tutorial&emsp;|</a>
    {% endif %}
  </span>
  </p>
</section>
{% endif %}
<div class='hr'>==================================================================================================================================================================</div>
{% if draft.id %}
<section id='main_form'>
  {% if form.errors %}
  <p>Who do you think you are?</p>
  {% endif %}

  <form id="new_draft" method="post" action="{% url 'iw_app:edit_draft' draft.id %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">|&emsp;submit_draft&emsp;|</button>
    <button type="submit" name="return_and_preview">|&emsp;submit_preview&emsp;|</button>
    &emsp;<span><a class="navigation" href="{% url 'iw_app:staging_all' %}">|&emsp;return_without_saving&emsp;|</a></span>
    <button type="submit" id='delete_button' name="delete_this_thing">|&emsp;delete_draft&emsp;|</button>
    <!--<input type="hidden" name="next" value="{% url 'iw_app:index' %}"/>-->
  </form>
</section>
{% elif article.id %}
<section id='main_form'>
  {% if form.errors %}
  <p>Who do you think you are?</p>
  {% endif %}

  <form id="new_draft" method="post" action="{% url 'iw_app:edit_article' article.id %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">|&emsp;submit_edit&emsp;|</button>
    <button type="submit" name="return_and_preview">|&emsp;submit_goto_article&emsp;|</button>
    &emsp;<span><a class="navigation" href="{% url 'iw_app:staging_all' %}">|&emsp;return_without_saving&emsp;|</a></span>
    <!--<button type="submit" id='delete_button' name="delete_this_thing">|&emsp;delete_draft&emsp;|</button>-->
    <!--<input type="hidden" name="next" value="{% url 'iw_app:index' %}"/>-->
  </form>
</section>
{% else %}
<section id='main_form'>
  {% if form.errors %}
  <p>Who do you think you are?</p>
  {% endif %}

  <form id="new_draft" method="post" action="{% url 'iw_app:new_draft' filter_m %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">|&emsp;submit_draft&emsp;|</button>
    &emsp;<span><a class="navigation" href="{% url 'iw_app:staging_all' %}">|&emsp;return_without_saving&emsp;|</a></span>
    <!--<input type="hidden" name="next" value="{% url 'iw_app:index' %}"/>-->
  </form>
</section>
{% endif %}
</main>
{% endblock content %}

iw_app/templates/iw_app/modified_base.html
{% load static %}
<html>

<head>
<link rel="stylesheet" type="text/css" href="{% static "iw_app/css/style_main.css" %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

{% if filter_mode == null %}
  <a href='{% url "iw_app:staging_all" %}' class='return_index'>|<span class='small'>&nbsp;&lArr;</span><span class='big'>&emsp;</span><span class='big'>&nbsp;Staging Area&emsp;</span><span class='small'>&nbsp;</span>|</a>
{% endif %}

<div class='login'>
{% if user.is_authenticated %}
  Hello, <span class="known_post">{{ user.username }}</span>&ensp;
  <a href="{% url 'users:logout'%}">|&emsp;log_out&emsp;|</a>&ensp;
{% else %}
  <a href="{% url 'users:login' %}">|&emsp;log_in / register&emsp;|</a>
{% endif %}

{% if request != null %}
  {% if request.get_full_path != "/site_information/"%}
    &ensp;<a href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
  {% else %}
    &ensp;<a class="focus" href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
  {% endif %}
{% else %}
    &ensp;<a href="{% url 'iw_app:information' %}">|&emsp;Info&emsp;|</a>
{% endif %}
</div>

{% block content %}



{% endblock content %}

</html>

iw_app/templates/iw_app/staging_area.html
{% extends "iw_app/base.html" %}

{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'iw_app/css/tutorial_style.css' %}">
<style>
  main{
    margin-top: 100px;
    width:100%;
    max-width: 1000px;
  }
  h6{
    margin-top: 0px;
    margin-bottom: 0px;
  }
  .section{
    margin-top: 20px;
  }
  .article{
    margin-bottom: 20px;
    position:relative;
  }

  .byline{
    display:inline-block;
  }

  .external_link{
    margin-top: 0px;
    margin-bottom: 10px;
    display:block;
  }

  .nav_button{
    margin-top: 0px;
    margin-bottom: 0px;
    text-align: right;
    display:block;
    margin-right: 5px;
  }
  span p{
    margin-top: 4px;
    margin-bottom: 4px;
    margin-right: 15px;
  }

  form {
    margin: 0px;
    padding: 0px;
  }
</style>
<main>
    <div class='section'>
      <div class='col span_2_of_4'>

        <div class='section'>
        <h4 class='focus'>All Public Drafts</h4>
        </div>

        {% for draft in drafts %}
        <div class='section'>
        <div class='col span_3_of_4 article'>
          <h6><a class='link_to_full_article' href="{% url 'iw_app:staging_indv' draft.id %}">{{ draft.article_name }}</a></h6>
          {% if draft.article_external_url %}
            <a class='external_link' href='{{draft.article_external_url}}'>{{draft.article_external_url}}</a>
          {% endif %}
          {% if draft.article_description %}
            <p class='external_link'>{{draft.article_description}}</p>
          {% endif %}
          <div class="timestamp">{{ draft.date_created|date:"r"}}&nbsp;</div>
          <a class="byline">
            {% for author in draft.name_author.all %}
              {{ author.username }}&ensp;
            {% empty %}
            {% endfor %}&nbsp;
          </a>
        </div>
        <div class='col span_1_of_4'>
          <form action="{% url 'iw_app:staging_all' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="vote_article" value="{{draft.id}}"/>
            <span class='nav_button'>{{draft.draft_vote}}&ensp;<a class='navigation' href="javascript:{}" onclick="this.parentNode.parentNode.submit();">|&emsp;&#128399;&emsp;|</a></span>
          </form>
          <!--<span class='nav_button'><p>{{draft.draft_vote}}</p></span>-->
          <!--<span class='nav_button'><a class='navigation'>|&emsp;&dArr;&emsp;|</a></span>-->
        </div>
        </div>
        {% empty %}
        {% endfor %}
      </div>
      <div class='col span_2_of_4'>

        <div class='section'>
        <h4 class='focus' >My Complete Articles</h4>
        </div>

        {% for article in my_articles %}
        <div class='section'>
        <div class='col span_3_of_4 article'>
          <h6><a class="link_to_full_article" href="{% url 'iw_app:article' article.id %}">{{ article.article_name }}</a></h6>
          {% if article.article_external_url %}
            <a class='external_link' href='{{article.article_external_url}}'>{{article.article_external_url}}</a>
          {% endif %}
          {% if article.article_description %}
            <p class='external_link'>{{article.article_description}}</p>
          {% endif %}
          <div class="timestamp">{{ article.date_created|date:"r"}}&nbsp;</div>
          <a class="byline">
            {% for author in article.name_author.all %}
              {{ author.username }}&ensp;
            {% empty %}
            {% endfor %}&nbsp;
          </a>
        </div>
        <div class='col span_1_of_4'>
          <span class='nav_button'><a class='navigation' href="{% url 'iw_app:edit_article' article.id %}">|&emsp;&#9998;&emsp;|</a></span>
        </div>
        </div>
        {% empty %}
        {% endfor %}

        <div class='section'>
        <h4 class='focus'>My Drafts</h4>
        </div>

        {% for draft in my_drafts%}
        <div class='section'>
        <div class='col span_3_of_4 article'>
          <h6><a class='link_to_full_article' href="{% url 'iw_app:staging_indv' draft.id %}">{{ draft.article_name }}</a></h6>
          {% if draft.article_external_url %}
            <a class='external_link' href='{{draft.article_external_url}}'>{{draft.article_external_url}}</a>
          {% endif %}
          {% if draft.article_description %}
            <p class='external_link'>{{draft.article_description}}</p>
          {% endif %}
          <div class="timestamp">{{ draft.date_created|date:"r"}}&nbsp;</div>
          <a class="byline">
            {% for author in draft.name_author.all %}
              {{ author.username }}&ensp;
            {% empty %}
            {% endfor %}&nbsp;
          </a>
        </div>
        <div class='col span_1_of_4'>
            <form action="{% url 'iw_app:staging_all' %}" method="post">
              {% csrf_token %}
              <span class='nav_button'>
              <input type="hidden" name="make_public_swap" value="{{draft.id}}"/>
              <a class='navigation' href="javascript:{}" onclick="this.parentNode.parentNode.submit();">{% if draft.make_public %}|&emsp;&#128473;&emsp;|{% else %}|&emsp;&#10003;&emsp;|{% endif %}</a>
              <a class='navigation' href="{% url 'iw_app:edit_draft' draft.id %}">|&emsp;&#9998;&emsp;|</a>
              &ensp;</span>
              <!--<button type='submit' class='navigation' name='change_public_state' value='{{draft.id}}'>|&emsp;&#10003;&emsp;|</button>-->
            </form>
        </div>
        </div>
        {% empty %}
        {% endfor %}

        <div class='section'>
        <h4 class='focus'>Author Tools</h4>
        </div>

        <a class='navigation' href="{% url 'iw_app:new_draft' %}">|&emsp;new draft&emsp;|</a>&emsp;
        <a class='navigation' href="{% static 'iw_app/author_downloads/static_templates.zip' %}">|&emsp;templates&emsp;|</a>
      </div>
    </div>
</main>
{% endblock content %}