interface_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # My Apps
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('iw_app.urls', namespace='iw_app'))
]

iw_app/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # add urls for pagination
    url(r'^(?P<page_id>\d+)/$', views.index, name='index'),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article, name='article'),
    # add urls for filter modes
    url(r'^(?P<filter_mode>p|c|n|o)/$', views.index, name='index'),
    url(r'^(?P<page_id>\d+)/(?P<filter_mode>p|c|n|o)/$', views.index, name='index'),
    # add url for site information board
    url(r'^site_information/$', views.about_contact, name='information'),
    # add urls for mod panel AND comment moderation panel
    url(r'^site_infrastructure/', include([
        #Redirects to a page will all flagged comments mods will have the option to delete or reset the flagged count to zero.
        url(r'^mod/$', views.content_moderation, name='content_moderation'),
        #This view will also show all of the authors created articles.
        url(r'^staging/$', views.article_staging_all, name='staging_all'),
        # This is an in-depth view into an individual article.
        url(r'^staging/(?P<staged_article>[0-9]+)/$', views.article_staging_individual, name='staging_indv'),
    ])),
    # add urls for article creation AND article editing
    url(r'^author_panel/', include([
        url(r'^new_draft/$', views.new_draft, name='new_draft'),
        url(r'^new_draft/(?P<filter_m>l|e|t)/$', views.new_draft, name='new_draft'),
        url(r'^edit_draft/(?P<draft_id>[0-9]+)/$', views.edit_draft, name='edit_draft'),
        url(r'^edit_article/(?P<article_id>[0-9]+)/$', views.edit_article, name='edit_article'),
    ])),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Register page
    url(r'^register/', views.register_view, name='register')
]

users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('iw_app:index'))

def register_view(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display a blank registration form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            print("form saved")
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('iw_app:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends "iw_app/base.html" %}

{% block content %}
  <style>
    main{
      margin-top: 100px;
    }
  </style>
  <main>
  <section>
  <p>don't have an acct. <a href="{% url 'users:register' %}"> Register </a></p>

  {% if form.errors %}
  <p>Who do you think you are?</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">|&emsp;Login&emsp;|</button>
    <input type="hidden" name="next" value="{% url 'iw_app:index' %}"/>
  </form>
</section>
  </main>
{% endblock content %}

users/templates/users/register.html
{% extends "iw_app/base.html" %}

{% load static %}
{% block content %}
<style>
  main{
    margin-top: 100px;
  }
</style>
<main>
<section>
  {% if form.errors %}
  <p>Who do you think you are?</p>
  {% endif %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">|&emsp;Register&emsp;|</button>
    <!--<input type="hidden" name="next" value="{% url 'iw_app:index' %}"/>-->
  </form>
</section>
</main>

{% endblock content %}